export const ACCOUNTABILITY_MESSAGE_TYPES = {
  MOTIVATION: "MOTIVATION",

  CHECKPOINT_NUDGE:
    "CHECKPOINT_NUDGE",

  REVIEW_REMINDER:
    "REVIEW_REMINDER",

  APPEAL_WARNING:
    "APPEAL_WARNING",

  SUCCESS_MESSAGE:
    "SUCCESS_MESSAGE",

  FAILURE_MESSAGE:
    "FAILURE_MESSAGE",
};