export const ACCOUNTABILITY_RULES = {
  MAX_REPORTS_PER_DAY: 1,

  // Future Rules
  MAX_AI_REVIEWS_PER_DAY: null,
  MAX_WITNESS_REVIEWS_PER_DAY: null,
  MAX_APPEALS_PER_CHALLENGE: null,
  MAX_ACTIVE_CHALLENGES: null,
};