export const AI_COACH_TYPES = {
  CONSISTENCY_COACH:
    "CONSISTENCY_COACH",

  WITNESS_COACH:
    "WITNESS_COACH",

  PROGRESS_COACH:
    "PROGRESS_COACH",

  REVIEW_COACH:
    "REVIEW_COACH",

  APPEAL_COACH:
    "APPEAL_COACH",
};

export default
  AI_COACH_TYPES;