export const AI_INSIGHT_TYPES = {
  CONSISTENCY: "CONSISTENCY",
  WITNESS_ENGAGEMENT: "WITNESS_ENGAGEMENT",
  CHALLENGE_HEALTH: "CHALLENGE_HEALTH",
  ACCOUNTABILITY_SUMMARY: "ACCOUNTABILITY_SUMMARY",
};

export default AI_INSIGHT_TYPES;