export const AI_NARRATIVE_TYPES = {
  PROGRESS_NARRATIVE:
    "PROGRESS_NARRATIVE",

  WITNESS_NARRATIVE:
    "WITNESS_NARRATIVE",

  ACCOUNTABILITY_NARRATIVE:
    "ACCOUNTABILITY_NARRATIVE",

  OUTCOME_NARRATIVE:
    "OUTCOME_NARRATIVE",

  MASTER_NARRATIVE:
    "MASTER_NARRATIVE",
};

export default
  AI_NARRATIVE_TYPES;