export const CHALLENGE_CATEGORIES = {
  WAKE_UP: "WAKE_UP",

  READING: "READING",

  FITNESS: "FITNESS",

  STUDY: "STUDY",

  MEDITATION: "MEDITATION",

  QUIT_SMOKING: "QUIT_SMOKING",

  CUSTOM: "CUSTOM",
};