 import {
  CHALLENGE_STATUS,
} from "./challengeStatus.js";

export const CHALLENGE_TRANSITIONS = {
  [CHALLENGE_STATUS.ACTIVE]: [
    CHALLENGE_STATUS.UNDER_REVIEW,
  ],

  [CHALLENGE_STATUS.UNDER_REVIEW]: [
    CHALLENGE_STATUS.COMPLETED,
    CHALLENGE_STATUS.REJECTED,
  ],

  [CHALLENGE_STATUS.REJECTED]: [
    CHALLENGE_STATUS.APPEALED,
  ],

  [CHALLENGE_STATUS.APPEALED]: [
    CHALLENGE_STATUS.COMPLETED,
    CHALLENGE_STATUS.FAILED,
  ],
};