import { CHALLENGE_STATUS } from "./challengeStatus.js";

export const ACTIVE_SLOT_STATUSES = [
  CHALLENGE_STATUS.PENDING_WITNESS,
  CHALLENGE_STATUS.ACTIVE,
  CHALLENGE_STATUS.UNDER_REVIEW,
  CHALLENGE_STATUS.APPEALED,
];