export const NOTIFICATION_TYPES = {
  CHALLENGE_CREATED: "CHALLENGE_CREATED",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  APPEAL_REVIEW_REQUIRED: "APPEAL_REVIEW_REQUIRED",
};

export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
};