export const REMINDER_TYPES = {
  CHECKPOINT_REMINDER: "CHECKPOINT_REMINDER",
  REVIEW_REMINDER: "REVIEW_REMINDER",
  APPEAL_REMINDER: "APPEAL_REMINDER",
};

export const REMINDER_STATUS = {
  PENDING: "PENDING",
  TRIGGERED: "TRIGGERED",
  EXPIRED: "EXPIRED",
};