export const WITNESS_ANALYTICS_EVENTS = {
  REVIEW_LINK_SHARED:
    "REVIEW_LINK_SHARED",

  REVIEW_LINK_OPENED:
    "REVIEW_LINK_OPENED",

  REVIEW_STARTED:
    "REVIEW_STARTED",

  REVIEW_SUBMITTED:
    "REVIEW_SUBMITTED",
};