 export const WITNESS_DECISION_REASON = {
  SUCCESS: "SUCCESS",
  UNKNOWN_ACTION: "UNKNOWN_ACTION",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",

  // Invitation
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_ACCEPTED:
    "INVITATION_ALREADY_ACCEPTED",
  INVITATION_ALREADY_DECLINED:
    "INVITATION_ALREADY_DECLINED",
  INVITATION_SUPERSEDED:
    "INVITATION_SUPERSEDED",

  // Challenge
  CHALLENGE_NOT_FOUND:
    "CHALLENGE_NOT_FOUND",
  CHALLENGE_NOT_PENDING_WITNESS:
    "CHALLENGE_NOT_PENDING_WITNESS",
  CHALLENGE_DEADLINE_PASSED:
    "CHALLENGE_DEADLINE_PASSED",

  // Review
  REVIEW_NOT_ALLOWED:
    "REVIEW_NOT_ALLOWED",
  REVIEW_ALREADY_SUBMITTED:
    "REVIEW_ALREADY_SUBMITTED",

  // Rejection
  REJECTION_REASON_REQUIRED:
    "REJECTION_REASON_REQUIRED",
  REJECTION_REASON_TOO_SHORT:
    "REJECTION_REASON_TOO_SHORT",
  REJECTION_REASON_TOO_LONG:
    "REJECTION_REASON_TOO_LONG",

  // Appeal
  APPEAL_NOT_ALLOWED:
    "APPEAL_NOT_ALLOWED",
  APPEAL_WINDOW_EXPIRED:
    "APPEAL_WINDOW_EXPIRED",
  APPEAL_ALREADY_SUBMITTED:
    "APPEAL_ALREADY_SUBMITTED",
};