export const NOTIFICATION_EVENTS = {
  CHALLENGE_CREATED:
    "CHALLENGE_CREATED",

  PROGRESS_REPORT_SUBMITTED:
    "PROGRESS_REPORT_SUBMITTED",

  REMINDER_TRIGGERED:
    "REMINDER_TRIGGERED",

  CHALLENGE_UNDER_REVIEW:
    "CHALLENGE_UNDER_REVIEW",

  CHALLENGE_APPROVED:
    "CHALLENGE_APPROVED",

  CHALLENGE_REJECTED:
    "CHALLENGE_REJECTED",

  APPEAL_SUBMITTED:
    "APPEAL_SUBMITTED",

  CHALLENGE_COMPLETED:
    "CHALLENGE_COMPLETED",

  CHALLENGE_FAILED:
    "CHALLENGE_FAILED",
};